name: cc-lint configuration publishing steps

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: set node version
        shell: bash -l {0}
        run: |
          echo "PRE: $(node -v)"
          nvm install
          echo "POST: $(node -v)"

      - name: install dependencies
        run: |
          npm ci

      - name: test package
        run: |
          npm test

      - name: publish package
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
